### PR TITLE
Enabling the HTTP-RPC server via variables

### LINKED ISSUE #61: [autonity-network] Enable the HTTP-RPC server via variables
### User story
As an engineer,
I want the HTTP-RPC server options to be enabled via variables,
So that I can deploy the HTTP-RPC server using options.

### Description
At the moment the HTTP-RPC server is hard-coded in the template and has no flexibility in deploying different validators or observers with the same chart. The relevant flags need to be taken into the values file.

### Acceptance criteria
- [x] Ensure the below flags are available to the end user [(original source)](https://geth.ethereum.org/docs/interface/command-line-options):
  - [x] `--http` Enable the HTTP-RPC server
  - [x] `--http.addr value` HTTP-RPC server listening interface (default: "localhost")
  - [x] `--http.port value` HTTP-RPC server listening port (default: 8545)
  - [x] `--http.api value` API's offered over the HTTP-RPC interface
  - [x] `--http.vhosts value` Comma separated list of virtual hostnames from which to accept requests (server enforced). Accepts '*' wildcard. (default: "localhost")  
- [x] Ensure the new flags are used in preference to the legacy aliased ones
- [x] Documentation updated with relevant/default values and description
- [x] Original values as default

### Related issues
- [[autonity-network] Enable the HTTP-RPC server via variables #60](https://github.com/clearmatics/charts-ose-helm3/issues/60)

### PR DESCRIPTION
**Pull request by Klazomenai**
### Changelog
Resolves #61 

### Submissions
* [x] Have you followed the guidelines in our [contributing document](CONTRIBUTING.md)?
* [x] Is the `branch` name the same as the Helm chart name that you will release?
* [x] Has your change only affected one Helm chart?
* [ ] Have you increased the version of the Helm chart `Chart.yaml`?
* [x] Have you updated the [changelog](CHANGELOG.md)?

Note: Not increasing the version in the Chart.yaml as this will form part of a wider release

### CODE REVIEW

**Comment by eastata** [comment]
Could we define autonity arguments as an array in variables ?
It can give us more flexibility
Also we can define default arguments array

**Review by eastata — APPROVED** [review]

**Comment by Klazomenai** [comment]
> Could we define autonity arguments as a list in variables ?
> It can give us more flexibility

Unsure what extra flexibility we'll get from that. Can you expand with a use case please.

**Comment by Klazomenai** [comment]
> Also we can define default arguments list

From: https://helm.sh/docs/chart_template_guide/functions_and_pipelines/

"In an actual chart, all static default values should live in the values.yaml". The defaults are in the `values.yaml` file.

**Comment by eastata** [comment]
> Unsure what extra flexibility we'll get from that. Can you expand with a use case please.

`helm install autonity-network --set autonity_args={"--gcmode","archive","--syncmode","full"}`
Where **autonity_args** could be any set of arguments

**Comment by Klazomenai** [comment]
> Where **autonity_args** could be any set of arguments

OK, understood. Unfortunately that is outside the scope of the original issue.

**Pull request merged**
